# -*- coding: utf-8 -*-
"""text_voice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HDjopgi8iIWnWek-CDJYCIKGW-j_5oy
"""

!pip install -q edge-tts langdetect

import edge_tts
import asyncio

async def get_voices():
    voices = await edge_tts.list_voices()
    return voices


voices = await get_voices()

print("Total voices:", len(voices))

for v in voices[:10]:
    print(v["ShortName"], "|", v["Locale"])

import edge_tts
from langdetect import detect
from IPython.display import Audio, display


async def text_to_voice(text):

    # detect language
    lang = detect(text)

    print("Detected language:", lang)

    # get all voices
    voices = await edge_tts.list_voices()

    voice = None

    # select matching language voice
    for v in voices:
        if v["Locale"].lower().startswith(lang):
            voice = v["ShortName"]
            break

    # fallback
    if voice is None:
        voice = "en-US-AriaNeural"

    print("Selected voice:", voice)

    communicate = edge_tts.Communicate(
        text=text,
        voice=voice
    )

    await communicate.save("reply.mp3")

    return "reply.mp3"


# USER INPUT LOOP

while True:

    user_text = input("\nEnter text (type exit to stop): ")

    if user_text.lower() == "exit":
        break

    audio_file = await text_to_voice(user_text)

    display(
        Audio(
            audio_file,
            autoplay=True
        )
    )

